version: '3'
services:
 store-be:
  build: .
  ports:
   - '${PORT}:${PORT}'
  env_file:
   - .env
  depends_on:
   - postgres

 postgres:
  image: postgres
  ports:
   - '5432:5432'
  environment:
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=${DB_NAME}
  volumes:
   - ./init-scripts:/docker-entrypoint-initdb.d
   - ./postgres-data:/var/lib/postgresql/data
